const withPrefix = action => `PROFILE/${action}`

export default {
  GET_USER_INFO: withPrefix('REDUCER/GET_USER_INFO'),
  SET_USER_INFO: withPrefix('REDUCER/SET_USER_INFO'),

  UPDATE_PROFILE: withPrefix('REDUCER/UPDATE_PROFILE'),
  UPDATE_PROFILE_SUCCESS: withPrefix('REDUCER/UPDATE_PROFILE_SUCCESS'),

  GET_USER_FACTORS: withPrefix('REDUCER/GET_USER_FACTORS'),
  GET_USER_FACTORS_SUCCESS: withPrefix('REDUCER/GET_USER_FACTORS_SUCCESS'),

  GET_DOCUMENT_CATEGORIES: withPrefix('REDUCER/GET_DOCUMENT_CATEGORIES'),
  SET_DOCUMENT_CATEGORIES: withPrefix('REDUCER/SET_DOCUMENT_CATEGORIES'),

  UPLOAD_DOCUMENT: withPrefix('REDUCER/UPLOAD_DOCUMENT'),
  UPLOAD_DOCUMENT_SUCCESS: withPrefix('REDUCER/UPLOAD_DOCUMENT_SUCCESS'),

  GET_UPLOADED_DOCS: withPrefix('REDUCER/GET_UPLOADED_DOCS'),
  SET_UPLOADED_DOCS: withPrefix('REDUCER/SET_UPLOADED_DOCS'),

}
