const withPrefix = action => `AUTHENTICATION/${action}`

export default {
  REQUEST_LOGIN: withPrefix('REDUCER/REQUEST_LOGIN'),
  REQUEST_LOGIN_SUCCESS: withPrefix('REDUCER/REQUEST_LOGIN_SUCCESS'),

  SET_OTP: withPrefix('REDUCER/SET_OTP'),

  CONFIRM_OTP: withPrefix('REDUCER/CONFIRM_OTP'),
  CONFIRM_OTP_SUCCESS: withPrefix('REDUCER/CONFIRM_OTP_SUCCESS'),

  SET_LOGIN_INFO: withPrefix('REDUCER/SET_LOGIN_INFO'),

  SET_LOGIN_NUMBER: withPrefix('REDUCER/SET_LOGIN_NUMBER'),

  REQUEST_LOGIN_WITH_PASSWORD: withPrefix('REDUCER/REQUEST_LOGIN_WITH_PASSWORD'),
}
